name: Building ISO (tianlu, daily)
run-name: Building ISO (tianlu, daily)

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '45 05 * * *'

jobs:
  i386:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Building
        run: |
          sudo bash build-squashfs.sh i386 unstable unaptss

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-i386-tianlu
          path: gxde.iso

      - name: Sourceforge Upload
        env:
          SourceforgeUser: ${{ secrets.SourceforgeUser }}
          SourceforgePassword: ${{ secrets.SourceforgePassword }}
        run: |
          sudo apt install sshpass rsync -y
          echo "Building Time: $(date)" > README.md
          mkdir -p ~/.ssh/
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh gxde.iso $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/i386
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh README.md $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/i386

  
  amd64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Building
        run: |
          sudo bash build-squashfs.sh amd64 unstable unaptss

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-amd64-tianlu
          path: gxde.iso

      - name: Sourceforge Upload
        env:
          SourceforgeUser: ${{ secrets.SourceforgeUser }}
          SourceforgePassword: ${{ secrets.SourceforgePassword }}
        run: |
          sudo apt install sshpass rsync -y
          echo "Building Time: $(date)" > README.md
          mkdir -p ~/.ssh/
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh gxde.iso $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/amd64
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh README.md $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/amd64

  arm64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Building
        run: |
          sudo bash build-squashfs.sh arm64 unstable unaptss

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-arm64-tianlu
          path: gxde.iso

      - name: Sourceforge Upload
        env:
          SourceforgeUser: ${{ secrets.SourceforgeUser }}
          SourceforgePassword: ${{ secrets.SourceforgePassword }}
        run: |
          sudo apt install sshpass rsync -y
          echo "Building Time: $(date)" > README.md
          mkdir -p ~/.ssh/
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh gxde.iso $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/arm64
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh README.md $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/arm64

  loong64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Config
        run: |
            sudo apt install debian-ports-archive-keyring debian-archive-keyring -y
            sudo cp /usr/share/keyrings/debian-ports-archive-keyring.gpg /usr/share/keyrings/debian-archive-keyring.gpg -v

      - name: Building
        run: |
          sudo bash build-squashfs.sh loong64 unstable unaptss

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-loong64-tianlu
          path: gxde.iso

      - name: Sourceforge Upload
        env:
          SourceforgeUser: ${{ secrets.SourceforgeUser }}
          SourceforgePassword: ${{ secrets.SourceforgePassword }}
        run: |
          sudo apt install sshpass rsync -y
          echo "Building Time: $(date)" > README.md
          mkdir -p ~/.ssh/
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh gxde.iso $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/loong64
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh README.md $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/loong64





