name: Building ISO (tianlu, daily)
run-name: Building ISO (tianlu, daily)

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '45 05 * * *'

jobs:
  i386:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Building
        run: |
          sudo bash build-squashfs.sh i386 unstable unaptss

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-i386-tianlu
          path: gxde.iso

      - name: Prepare SFTP Path
        run: |
          mkdir -p tianlu/i386
          cp gxde.iso tianlu/i386
          echo "Building Time: $(date)" > tianlu/i386/README.md

      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: frs.sourceforge.net
          username: ${{ secrets.SourceforgeUser }}
          password: ${{ secrets.SourceforgePassword }}
          port: 22
          uploads: |
            tianlu => /home/frs/project/gxde-os-daily/
  
  amd64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Building
        run: |
          sudo bash build-squashfs.sh amd64 unstable unaptss

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-amd64-tianlu
          path: gxde.iso

      - name: Prepare SFTP Path
        run: |
          mkdir -p tianlu/amd64
          cp gxde.iso tianlu/amd64
          echo "Building Time: $(date)" > tianlu/amd64/README.md

      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: frs.sourceforge.net
          username: ${{ secrets.SourceforgeUser }}
          password: ${{ secrets.SourceforgePassword }}
          port: 22
          uploads: |
            tianlu => /home/frs/project/gxde-os-daily/

  arm64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Building
        run: |
          sudo bash build-squashfs.sh arm64 unstable unaptss

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-arm64-tianlu
          path: gxde.iso

      - name: Prepare SFTP Path
        run: |
          mkdir -p tianlu/arm64
          cp gxde.iso tianlu/arm64
          echo "Building Time: $(date)" > tianlu/arm64/README.md

      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: frs.sourceforge.net
          username: ${{ secrets.SourceforgeUser }}
          password: ${{ secrets.SourceforgePassword }}
          port: 22
          uploads: |
            tianlu => /home/frs/project/gxde-os-daily/

  loong64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Config
        run: |
            sudo apt install debian-ports-archive-keyring debian-archive-keyring -y
            sudo cp /usr/share/keyrings/debian-ports-archive-keyring.gpg /usr/share/keyrings/debian-archive-keyring.gpg -v

      - name: Building
        run: |
          sudo bash build-squashfs.sh loong64 unstable unaptss

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-loong64-tianlu
          path: gxde.iso

      - name: Prepare SFTP Path
        run: |
          mkdir -p tianlu/loong64
          cp gxde.iso tianlu/loong64
          echo "Building Time: $(date)" > tianlu/loong64/README.md

      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: frs.sourceforge.net
          username: ${{ secrets.SourceforgeUser }}
          password: ${{ secrets.SourceforgePassword }}
          port: 22
          uploads: |
            tianlu => /home/frs/project/gxde-os-daily/





