name: Building ISO (tianlu, daily)
run-name: Building ISO (tianlu, daily)

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '45 05 * * *'

jobs:
  i386-tianlu:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Building
        run: |
          sudo bash build-squashfs.sh i386 tianlu unaptss
          mv gxde.iso gxde-os-i386-tianlu.iso

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-i386-tianlu
          path: gxde-os-i386-tianlu.iso

      - name: Sourceforge Upload
        env:
          SourceforgeUser: ${{ secrets.SourceforgeUser }}
          SourceforgePassword: ${{ secrets.SourceforgePassword }}
        run: |
          sudo apt install sshpass rsync -y
          echo "Building Time: $(date)" > README.md
          mkdir -p ~/.ssh/
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh gxde-os-i386-tianlu.iso $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/i386
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh README.md $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/i386

  
  amd64-tianlu:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Building
        run: |
          sudo bash build-squashfs.sh amd64 tianlu unaptss
          mv gxde.iso gxde-os-amd64-tianlu.iso

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-amd64-tianlu
          path: gxde-os-amd64-tianlu.iso

      - name: Sourceforge Upload
        env:
          SourceforgeUser: ${{ secrets.SourceforgeUser }}
          SourceforgePassword: ${{ secrets.SourceforgePassword }}
        run: |
          sudo apt install sshpass rsync -y
          echo "Building Time: $(date)" > README.md
          mkdir -p ~/.ssh/
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh gxde-os-amd64-tianlu.iso $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/amd64
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh README.md $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/amd64

  arm64-tianlu:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Building
        run: |
          sudo bash build-squashfs.sh arm64 tianlu unaptss
          mv gxde.iso gxde-os-arm64-tianlu.iso

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-arm64-tianlu
          path: gxde-os-arm64-tianlu.iso

      - name: Sourceforge Upload
        env:
          SourceforgeUser: ${{ secrets.SourceforgeUser }}
          SourceforgePassword: ${{ secrets.SourceforgePassword }}
        run: |
          sudo apt install sshpass rsync -y
          echo "Building Time: $(date)" > README.md
          mkdir -p ~/.ssh/
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh gxde-os-arm64-tianlu.iso $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/arm64
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh README.md $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/arm64

  mips64el-tianlu:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Building
        run: |
          sudo bash build-squashfs.sh mips64el tianlu unaptss
          mv gxde.iso gxde-os-mips64el-tianlu.iso

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-mips64el-tianlu
          path: gxde-os-mips64el-tianlu.iso

      - name: Sourceforge Upload
        env:
          SourceforgeUser: ${{ secrets.SourceforgeUser }}
          SourceforgePassword: ${{ secrets.SourceforgePassword }}
        run: |
          sudo apt install sshpass rsync -y
          echo "Building Time: $(date)" > README.md
          mkdir -p ~/.ssh/
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh gxde-os-mips64el-tianlu.iso $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/mips64el
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh README.md $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/mips64el

  loong64-tianlu:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Config
        run: |
            sudo apt install debian-ports-archive-keyring debian-archive-keyring -y
            sudo cp /usr/share/keyrings/debian-ports-archive-keyring.gpg /usr/share/keyrings/debian-archive-keyring.gpg -v

      - name: Building
        run: |
          sudo bash build-squashfs.sh loong64 tianlu unaptss
          mv gxde.iso gxde-os-loong64-tianlu.iso

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-loong64-tianlu
          path: gxde-os-loong64-tianlu.iso

      - name: Sourceforge Upload
        env:
          SourceforgeUser: ${{ secrets.SourceforgeUser }}
          SourceforgePassword: ${{ secrets.SourceforgePassword }}
        run: |
          sudo apt install sshpass rsync -y
          echo "Building Time: $(date)" > README.md
          mkdir -p ~/.ssh/
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh gxde-os-loong64-tianlu.iso $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/loong64
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh README.md $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/loong64


  loong64-meimei:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Config
        run: |
            sudo apt install debian-ports-archive-keyring debian-archive-keyring -y
            sudo cp /usr/share/keyrings/debian-ports-archive-keyring.gpg /usr/share/keyrings/debian-archive-keyring.gpg -v

      - name: Building
        run: |
          sudo bash build-squashfs.sh loong64 meimei unaptss
          mv gxde.iso gxde-os-loong64-meimei.iso

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-loong64-meimei
          path: gxde-os-loong64-meimei.iso

      - name: Sourceforge Upload
        env:
          SourceforgeUser: ${{ secrets.SourceforgeUser }}
          SourceforgePassword: ${{ secrets.SourceforgePassword }}
        run: |
          sudo apt install sshpass rsync -y
          echo "Building Time: $(date)" > README.md
          mkdir -p ~/.ssh/
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh gxde-os-loong64-meimei.iso $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/meimei/loong64
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh README.md $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/tianlu/loong64

  amd64-zhuangzhuang:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Building
        run: |
          sudo bash build-squashfs.sh amd64 zhuangzhuang unaptss
          mv gxde.iso gxde-os-amd64-zhuangzhuang.iso

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-amd64-zhuangzhuang
          path: gxde-os-amd64-zhuangzhuang.iso

      - name: Sourceforge Upload
        env:
          SourceforgeUser: ${{ secrets.SourceforgeUser }}
          SourceforgePassword: ${{ secrets.SourceforgePassword }}
        run: |
          sudo apt install sshpass rsync -y
          echo "Building Time: $(date)" > README.md
          mkdir -p ~/.ssh/
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh gxde-os-amd64-zhuangzhuang.iso $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/zhuangzhuang/amd64
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh README.md $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/zhuangzhuang/amd64

  arm64-zhuangzhuang:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Building
        run: |
          sudo bash build-squashfs.sh arm64 zhuangzhuang unaptss
          mv gxde.iso gxde-os-arm64-zhuangzhuang.iso

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-arm64-zhuangzhuang
          path: gxde-os-arm64-zhuangzhuang.iso

      - name: Sourceforge Upload
        env:
          SourceforgeUser: ${{ secrets.SourceforgeUser }}
          SourceforgePassword: ${{ secrets.SourceforgePassword }}
        run: |
          sudo apt install sshpass rsync -y
          echo "Building Time: $(date)" > README.md
          mkdir -p ~/.ssh/
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh gxde-os-arm64-zhuangzhuang.iso $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/zhuangzhuang/arm64
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh README.md $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/zhuangzhuang/arm64

  mips64el-zhuangzhuang:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Building
        run: |
          sudo bash build-squashfs.sh mips64el zhuangzhuang unaptss
          mv gxde.iso gxde-os-mips64el-zhuangzhuang.iso

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: gxde-os-mips64el-zhuangzhuang
          path: gxde-os-mips64el-zhuangzhuang.iso

      - name: Sourceforge Upload
        env:
          SourceforgeUser: ${{ secrets.SourceforgeUser }}
          SourceforgePassword: ${{ secrets.SourceforgePassword }}
        run: |
          sudo apt install sshpass rsync -y
          echo "Building Time: $(date)" > README.md
          mkdir -p ~/.ssh/
          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh gxde-os-mips64el-zhuangzhuang.iso $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/zhuangzhuang/mips64el
          sshpass -p "$SourceforgePassword" rsync -avP -e ssh README.md $SourceforgeUser@frs.sourceforge.net:/home/frs/project/gxde-os-daily/zhuangzhuang/mips64el
